config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  resources :users, only: %i[index]

  root to: 'articles#index'
  resources :articles, only: %i[index show]

  resources :groups, only: %i[index show]

  resources :subjects, only: %i[index]

  resources :courses, only: %i[index show] do
    resources :themes, except: %i[index show] do
      resources :lessons, except: %i[index show]
    end
  end

  resources :hometasks

  resources :timeslots, only: %i[index]

  resources :achievements, except: %i[index show]
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  def index
    if current_user.student?
      @courses = current_user.group.courses.includes(:subject)
    elsif current_user.teacher?
      @courses = current_user.courses.includes(:group)
    else
      redirect_to root_path
    end
  end

  def show
    @course = Course.includes('group', 'subject', 'user').find(params[:id])
    @title = t('activerecord.models.course.one')
    redirect_to root_path if redirect?
  end

  private

  def redirect?
    !@course.displayed || @course.student_access_forbidden?(current_user)
  end
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/views/courses/_course-header.html.erb
<table class="course-header">
  <tbody>
  <tr>
    <td class="col-md-3">
      <a href=<%= group_path @course.group.id %> >
        <%= "#{@course.group.number}-#{@course.group.parallel}" %>
      </a>
    </td>
    <td class="col-md-4">
      <%= t("subjects.#{@course.subject.name}") %>
    </td>
    <td class="col-md-5">
      <%= "#{@course.user.surname} #{@course.user.name}" %>
    </td>
  </tr>
  </tbody>
</table>

app/views/courses/_student-journal.html.erb
<div id="table-scroll" class="table-scroll">
  <div class="table-wrap">
    <table class="table table-hover table-bordered journal-table">
    <!--<table class="table table-hover table-bordered journal-table">-->
      <thead class="journal-thead">
        <tr>
          <th class="topic fixed">
            <%= t('activerecord.models.theme.other') %>
          </th>
          <% @course.themes.order(:id).each do |theme| %>
            <th colspan="<%= theme.lessons.count * 2 %>">
              <%= theme.id %>
            </th>
          <% end %>
        </tr>
        <tr>
          <th class="topic fixed">
            <%= t('activerecord.models.lesson.other') %>
          </th>
          <% @course.themes.each do |theme| %>
            <% theme.lessons.each do |lesson| %>
              <th colspan="2">
                <%= lesson.date ? lesson.date.strftime("%e.%m") : '--.--' %>
              </th>
            <% end %>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% student = current_user %>
        <tr class="student-row">
          <td class="student-name fixed">
            <%= "#{student.surname}" %> <%= "#{student.name}" %>
          </td>
          <% @course.themes.each do |theme| %>
            <% theme.lessons.each do |lesson| %>
              <% ach = @course.achievements_hash[lesson.id][student.id] %>
              <td class="points center <%= ach[:type] if ach %>">
                <%= ach[:points] if ach %>
              </td>
              <td class="attendance center">
                <%= 'н' if ach && !ach[:attendance] %>
              </td>
            <% end %>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/courses/_student.html.erb
<%= image_tag course.subject.image %>
<div class="course-name">
  <%= t("subjects.#{course.subject.name}") %>
</div>

app/views/courses/_teacher-journal.html.erb
<div id="table-scroll" class="table-scroll">
  <div class="table-wrap">
    <table class="table table-hover table-bordered journal-table">
    <!--<table class="table table-hover table-bordered journal-table">-->
      <thead class="journal-thead">
        <tr>
          <th class="topic fixed">
            <%= t('activerecord.models.theme.other') %>
          </th>
          <% @course.themes.order(:id).each do |theme| %>
            <th colspan="<%= theme.lessons.count * 2 + 1 %>">
              <%= link_to theme.id, edit_course_theme_path(id: theme, course_id: @course) %>
            </th>
          <% end %>
          <th class="plus-item">
            <%= link_to image_tag('plus.png'), new_course_theme_path(course_id: @course), class: 'plus-link' %>
          </th>
        </tr>
        <tr>
          <th class="topic fixed">
            <%= t('activerecord.models.lesson.other') %>
          </th>
          <% @course.themes.each do |theme| %>
            <% theme.lessons.each do |lesson| %>
              <th colspan="2">
                <% lesson_link = lesson.date ? lesson.date.strftime("%e.%m") : '--.--' %>
                <%= link_to lesson_link, edit_course_theme_lesson_path(id: lesson, theme_id: theme.id, course_id: @course) %>
              </th>
            <% end %>
            <th class="plus-item">
              <%= link_to image_tag('plus.png'), new_course_theme_lesson_path(theme_id: theme.id, course_id: @course.id), class: 'plus-link' %>
            </th>
          <% end %>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @course.group.users.each do |student| %>
          <tr class="student-row">
            <td class="student-name fixed">
              <%= "#{student.surname}" %> <%= "#{student.name}" %>
            </td>
            <% @course.themes.each do |theme| %>
              <% theme.lessons.each do |lesson| %>
                <% ach = @course.achievements_hash[lesson.id][student.id] %>
                <td class="points center <%= ach[:type] if ach %>">
                  <%= ach[:points] if ach %>
                </td>
                <td class="attendance center">
                  <%= 'н' if ach && !ach[:attendance] %>
                </td>
              <% end %>
              <td class="center"></td>
            <% end %>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/courses/_teacher.html.erb
<%= image_tag "groups/#{course.group.number}.png", class: 'group-img' %>
<%= image_tag "groups/#{course.group.parallel}.png", class: 'group-img' %>
<div class="course-name">
  <%= t("subjects.#{course.subject.name}") %>
</div>

app/views/courses/index.html.erb
<% @title = t('activerecord.models.course.other') %>
<h1><%= @title %></h1>
<section class="course-section">
    <% @courses.in_groups_of(4).each do |group| %>
      <div class="row">
        <% group.each do |course| %>
          <% if course %>
            <a href=<%= course_path course %> >
              <div class="course-item col-md-3">
                <%= render "#{current_user.role}", :course => course %>
              </div>
            </a>
          <% end %>
        <% end %>
      </div>
    <% end %>
</section>

app/views/courses/show.html.erb
<%= render 'course-header' %>

<%= render 'teacher-journal' if current_user.teacher? %>

<%= render 'student-journal' if current_user.student? %>

<%= link_to t(:back), courses_path, class: 'btn btn-info back-btn' %>