config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  resources :users, only: %i[index]

  root to: 'articles#index'
  resources :articles, only: %i[index show]

  resources :groups, only: %i[index show]

  resources :subjects, only: %i[index]

  resources :courses, only: %i[index show] do
    resources :themes, except: %i[index show] do
      resources :lessons, except: %i[index show]
    end
  end

  resources :hometasks

  resources :timeslots, only: %i[index]

  resources :achievements, except: %i[index show]
end

app/models/achievement.rb
# frozen_string_literal: true

class Achievement < ApplicationRecord
  belongs_to :user, -> { User.student }, inverse_of: :achievements
  belongs_to :lesson
  POINTS_RANGE = 1..12
  POINTS_LENGTH_RANGE = 1..2

  KINDS = %w[normal notebook thematic semester year].freeze

  validates :points, inclusion: { in: POINTS_RANGE }
  validates :points, length: { in: POINTS_LENGTH_RANGE }
  validates :attendance, inclusion: { in: [true, false] }

  enum kind: KINDS
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :topic, length: { in: 5..40 }
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :subject, optional: false
  belongs_to :group, optional: false
  belongs_to :user, -> { User.teacher }, inverse_of: false, optional: false
  has_many :timeslots, dependent: :nullify
  has_many :themes, dependent: :destroy

  validates :group_id, :subject_id, :user_id, presence: true

  def student_access_forbidden?(user)
    user.student? && group_id != user.group_id
  end

  def achievements_hash
    hash = {}
    themes.each do |theme|
      theme.lessons.each do |lesson|
        hash[lesson.id] = {}
        lesson.achievements.each do |ach|
          hash[lesson.id][ach.user.id] = { points: ach.points, type: ach.kind, attendance: ach.attendance }
        end
      end
    end
    hash
  end
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :courses, dependent: :nullify
  has_many :subjects, through: :courses
  has_many :users, -> { User.student }, inverse_of: false

  NUMBER_LENGTH_RANGE   = 1..2
  NUMBER_RANGE          = 1..12

  PARALLEL_LENGTH_RANGE = 1
  PARALLELS             = %w[a b c].freeze

  validates :number, :parallel, presence: true
  validates :number, length: { in: NUMBER_LENGTH_RANGE }
  validates :number, inclusion: { in: NUMBER_RANGE }
  validates :number, uniqueness: { scope: :parallel }
  validates :parallel, length: { is: PARALLEL_LENGTH_RANGE }
  validates :parallel, inclusion: { in: PARALLELS }

  def name
    "#{number}#{parallel}"
  end
end

app/models/hometask.rb
# frozen_string_literal: true

class Hometask < ApplicationRecord
  belongs_to :lesson
  validates :description, presence: true
  validates :description, length: { minimum: 3 }
  scope :for_course, lambda { |course|
                       joins(:lesson).where(lessons: { theme_id: course.themes })
                     }
  def subject_name
    lesson.theme.course.subject.name
  end

  def group_name
    lesson.theme.course.group.name
  end
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :theme
  has_one :hometask, dependent: :destroy
  has_many :achievements, dependent: :destroy
  validates :topic, presence: true
  validates :topic, length: { in: 5..40 }
  scope :without_hometask, lambda {
                             left_outer_joins(:hometask).where(hometasks: { id: nil })
                           }
  scope :for_courses, lambda { |courses|
                        courses = courses.to_a.map!(&:id)
                        left_outer_joins(:theme).where(themes: { course_id: courses })
                      }
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  has_many :courses, dependent: :nullify
  has_many :groups, through: :courses
  has_many :users, -> { User.teacher }, inverse_of: false, through: :courses

  validates :name, :image, presence: true
  validates :name, length: { in: 3..30 },
                   uniqueness: true,
                   format: { with: /\A[a-z_]+\z/,
                             message: 'Only a-z letters and _ symbol allowed' }
end

app/models/theme.rb
# frozen_string_literal: true

class Theme < ApplicationRecord
  belongs_to :course, optional: false

  has_many :lessons, dependent: :destroy

  LENGTH_RANGE = 5..40
  validates :topic, presence: true, length: { in: LENGTH_RANGE }
  validates :course, presence: true
end

app/models/timeslot.rb
# frozen_string_literal: true

class Timeslot < ApplicationRecord
  belongs_to :course
  DAYS = %w[monday tuesday wednesday thursday friday].freeze
  NUMBERS = %w[1 2 3 4 5 6 7 8 9].freeze

  validates :number, inclusion: { in: NUMBERS }
  validates :day, inclusion: { in: DAYS }
  validates :day, uniqueness: { scope: [:number, :group_id] }
  before_validation :set_group_id

  enum day: DAYS
  enum number: NUMBERS

  private

  def set_group_id
    self.group_id = course.group_id
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :group, optional: true

  has_many :courses, dependent: :nullify
  has_many :groups, through: :courses
  has_many :subjects, through: :courses

  has_many :achievements, dependent: :destroy

  NAME_LENGTH_RANGE = 2..30
  EMAIL_LENGTH_RANGE = 6..40
  ROLES = %w[student curator teacher mentor].freeze

  # validates :group_id, presence: true, if: -> { self.student? }

  validates :name, :surname, :email, presence: true
  validates :name, length: { in: NAME_LENGTH_RANGE }
  validates :surname, length: { in: NAME_LENGTH_RANGE }
  validates :email, length: { in: EMAIL_LENGTH_RANGE }
  validates :email, uniqueness: true
  validates :approved, inclusion: { in: [true, false] }
  validates :role, inclusion: { in: ROLES }

  enum role: ROLES

  def hometasks(collect_option)
    hometasks = []
    if student?
      hometasks = send(collect_option, hometasks, group.courses)
    elsif teacher?
      hometasks = send(collect_option, hometasks, courses)
    end
    hometasks
  end

  def lessons
    Lesson.for_courses(courses)
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if approved?
      super
    else
      :not_approved
    end
  end

  private

  def collect_last(hometasks, enumerator)
    enumerator.each do |course|
      hometasks << Hometask.for_course(course).last
    end
    hometasks
  end
  # def collect_all(hometasks, enumerator)
  #   enumerator.each do |course|
  #     hometasks << Hometask.for_course(course)
  #   end
  #   hometasks
  # end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/hometasks_helper.rb
# frozen_string_literal: true

module HometasksHelper
end

app/helpers/lessons_helper.rb
# frozen_string_literal: true

module LessonsHelper
end

app/helpers/subjects_helper.rb
# frozen_string_literal: true

module SubjectsHelper
end

app/helpers/themes_helper.rb
# frozen_string_literal: true

module ThemesHelper
end

app/helpers/timeslots_helper.rb
# frozen_string_literal: true

module TimeslotsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="locale-links">
    <%= link_to image_tag('subjects/english.png', size: '50x50'), '?locale=en', class: 'right' %>
    <%= link_to image_tag('subjects/ukrainian.png', size: '50x50'), '?locale=ua', class: 'right'  %>

    <% if user_signed_in? %>
      <%= link_to image_tag('exit.png', size: '47x47'), destroy_user_session_path, method: :delete, class: 'right' %>
    <% else %>
      <%= link_to image_tag('plus.png', size: '47x47'), new_user_session_path, class: 'right' %>
    <% end %>
  </div>
  <h1 class="header-title">
    <%= link_to t(:title), root_path, class: 'header-link'%>
  </h1>
  <div class="btn-group btn-group-justified" id="nav_row" role="group">
    <!--TODO: customize links list by user role -->
    <%= link_to t('menu.home'), root_path, class: 'btn btn-info' %>
    <%= link_to t('menu.courses'), courses_path, class: 'btn btn-info' %>
    <%= link_to t('menu.hometasks'), hometasks_path, class: 'btn btn-info' %>
    <%= link_to t('menu.group'), groups_path, class: 'btn btn-info' %>
    <%= link_to t('menu.timetable'), timeslots_path, class: 'btn btn-info' %>
    <%= link_to t('menu.teachers'), users_path, class: 'btn btn-info' %>
    <%= link_to t('menu.about_us'), '#', class: 'btn btn-info' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || t(:title) %></title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap 3 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="main container">
      <% if flash.present? %>
        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %> alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= value %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </main>

    <footer class="footer">
      <span> <%= t('all_rights_reserved') %> &copy; 2018</span>
    </footer>
  </body>
</html>